apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-rzco
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-rzco
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-rzco
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-rzco
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-rzco
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gxln-tenant/rhtap-demo-app/hacbs-test-project-rzco@sha256:e24d55d100cce1a4b13fb43c4378f8b599798f6142b8090fbfe54a15a8a76458
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
