apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-rzco
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gxln-tenant/rhtap-demo-app/hacbs-test-project-rzco@sha256:0ac4288243ac6bae6eb2ba644b7d48064ae76705cc901c81b71b04e9626f5b7e
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
