apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-rzco
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gxln-tenant/rhtap-demo-app/hacbs-test-project-rzco@sha256:b9094d1767f78ea65e7f4e8738868e2cee7bdf164d1f9c8be1fdb67d772c00ca
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
